name: Galactic Create Debs

on: 
  push:
    tags:
      - v*

jobs:
  galactic:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: galactic
      - run: sudo pip install "websockets>=13.0"
      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: galactic
          vcs-repo-file-url: https://raw.githubusercontent.com/ros2/ros2/galactic/ros2.repos
          skip-tests: true
      - uses: actions/checkout@v4
        with:
          path: fkie-multi-agent-suite
      - name: Create debian packages
        run: |
          source /opt/ros/galactic/setup.bash
          bash create_debs.sh
        shell: bash
        working-directory: fkie-multi-agent-suite
      - name: Upload debs to release ${{ github.ref }}
        uses: svenstaro/upload-release-action@v2
        with:
          file: fkie-multi-agent-suite/ros-galactic-fkie-mas-*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

