name: Humble Build

on: [push, pull_request]

jobs:
  humble:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - run: sudo pip install "websockets>=13.0"
      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: humble
          skip-tests: true

