name: Jazzy Build

on: [push, pull_request]

jobs:
  jazzy:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:noble
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy
      - run: sudo pip install "websockets>=13.0" --break-system-packages
      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: jazzy
          skip-tests: true
      - uses: actions/setup-node@v4
      - run: |
          npm install
          npm run build:linux
        working-directory: ${{ steps.action_ros_ci_step.outputs.ros-workspace-directory-name }}/src/fkie-multi-agent-suite/fkie_mas_gui
